/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-high": "#e7e8e9",
        "surface-container-low": "#f3f4f5",
        "primary": "#00236f",
        "primary-container": "#1e3a8a",
        "on-secondary": "#ffffff",
        "on-primary-fixed-variant": "#264191",
        "on-primary-fixed": "#00164e",
        "surface-bright": "#f8f9fa",
        "on-tertiary": "#ffffff",
        "primary-fixed-dim": "#b6c4ff",
        "secondary-fixed": "#6ffbbe",
        "on-tertiary-fixed": "#141b2b",
        "surface-tint": "#4059aa",
        "surface-container-highest": "#e1e3e4",
        "on-secondary-fixed": "#002113",
        "background": "#f8f9fa",
        "on-error-container": "#93000a",
        "inverse-surface": "#2e3132",
        "on-tertiary-container": "#a5acc0",
        "error-container": "#ffdad6",
        "on-tertiary-fixed-variant": "#404758",
        "tertiary-fixed-dim": "#c0c6db",
        "tertiary": "#232a3a",
        "inverse-primary": "#b6c4ff",
        "tertiary-container": "#394051",
        "on-surface-variant": "#444651",
        "tertiary-fixed": "#dce2f7",
        "on-surface": "#191c1d",
        "on-secondary-fixed-variant": "#005236",
        "on-primary-container": "#90a8ff",
        "on-primary": "#ffffff",
        "primary-fixed": "#dce1ff",
        "surface-container-lowest": "#ffffff",
        "outline": "#757682",
        "surface-container": "#edeeef",
        "surface-dim": "#d9dadb",
        "error": "#ba1a1a",
        "surface-variant": "#e1e3e4",
        "outline-variant": "#c5c5d3",
        "on-error": "#ffffff",
        "secondary-fixed-dim": "#4edea3",
        "on-secondary-container": "#00714d",
        "secondary-container": "#6cf8bb",
        "surface": "#f8f9fa",
        "on-background": "#191c1d",
        "inverse-on-surface": "#f0f1f2",
        "secondary": "#006c49"
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
      }
    },
  },
  plugins: [],
}